### ISSUE TITLE
头文件依旧包含Arduino.h

### ISSUE THREAD

**Issue by ohhh-yang** [HuXioAn/SimpleFOC-ESP-IDF#1]
无法运行，依旧需要Arduino框架，IDF无法直接运行

**Comment by HuXioAn** [comment]
不好意思，此项目中道崩卒，还不能用…

**Comment by ohhh-yang** [comment]
我现在就是用idf搞这个三相无刷电机，网上都没有找到simplefoc移植的😭。能提供一下你移植的思路不，我不想手敲一个电机的操作库啊啊啊😣😣



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月12日(周日) 晚上9:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HuXioAn/SimpleFOC-ESP-IDF] 头文件依旧包含Arduino.h (Issue #1)




 
不好意思，此项目中道崩卒，还不能用…

**Comment by HuXioAn** [comment]
我当时在dev分支里做了一些工作，但是要考虑的还是很多，比如他是cpp，要让idf改成cpp模式，后面就是针对Arduino.h的实现进行部分修改，其实本身Arduino就是idf实现。只是simplefoc调用有些复杂。
好久没看了，大部分记不得了。😭
